1. Initialize an empty array with size 2X2.

In [ ]:
array = [[None, None], [None, None]]
print(array)


[[None, None], [None, None]]


2. Initialize an all one array with size 4X2.

In [ ]:
array = [[1, 1] for _ in range(4)]
print(array)


[[1, 1], [1, 1], [1, 1], [1, 1]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
import numpy as np


shape = (4, 2)
fill_value = 7
dtype = int

array = np.full(shape, fill_value, dtype=dtype)

print(array)


[[7 7]
 [7 7]
 [7 7]
 [7 7]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
import numpy as np

# Example array
array = np.array([[1, 2], [3, 4]])

# Create a new array of zeros with the same shape and type
zero_array = np.zeros_like(array)

print(zero_array)


[[0 0]
 [0 0]]


In [ ]:
#question_5
import numpy as np

# Example array
array = np.array([[1, 2], [3, 4]])

# Create a new array of ones with the same shape and type
ones_array = np.ones_like(array)

print(ones_array)


[[1 1]
 [1 1]]


In [ ]:
#question_6
import numpy as np

# Existing list
new_list = [1, 2, 3, 4]

# Convert to a numpy array
array = np.array(new_list)

print(array)



[1 2 3 4]


problem 2

In [ ]:
#question_1
import numpy as np

# Create an array with values from 10 to 49
array = np.arange(10, 50)

print(array)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#question_2
import numpy as np

# Create an array with values from 0 to 8
array = np.arange(9)

# Reshape it into a 3x3 matrix
matrix = array.reshape(3, 3)

print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#question_3
import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)

print(identity_matrix)




[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#question_4
import numpy as np

# Create a random array of size 30 with values between 0 and 1
random_array = np.random.random(30)

# Calculate the mean of the array
mean_value = random_array.mean()

print("Random Array:", random_array)
print("Mean of the array:", mean_value)



Random Array: [0.47078129 0.97793324 0.80564616 0.87190844 0.29500989 0.53977138
 0.72325435 0.59981117 0.02876195 0.18566848 0.79378623 0.68091326
 0.63012479 0.02084351 0.95446227 0.10050364 0.97227639 0.01867309
 0.00557943 0.8312787  0.97288823 0.17666076 0.26292666 0.3850976
 0.70434519 0.66620239 0.7384883  0.31613394 0.04246593 0.91244038]
Mean of the array: 0.5228212344689569


In [ ]:
#question_5
import numpy as np

# Create a 10x10 array with random values between 0 and 1
random_array = np.random.random((10, 10))

# Find the minimum and maximum values in the array
min_value = random_array.min()
max_value = random_array.max()

print("Random 10x10 Array:\n", random_array)
print("Minimum value:", min_value)
print("Maximum value:", max_value)



Random 10x10 Array:
 [[0.18139782 0.8402575  0.91832002 0.42445225 0.98185909 0.69530417
  0.19431924 0.82267815 0.80458715 0.90031419]
 [0.15420914 0.6874574  0.52075359 0.5769144  0.34271623 0.8214769
  0.30177334 0.45907431 0.09233515 0.45628006]
 [0.47990301 0.33498992 0.58053595 0.52711979 0.32482263 0.15651784
  0.53646598 0.53450004 0.48005642 0.11649287]
 [0.31509001 0.55228497 0.68959395 0.31331665 0.87576854 0.75945509
  0.52313461 0.36508225 0.38634368 0.06420848]
 [0.17611867 0.87000281 0.64566213 0.01281692 0.45833323 0.32703555
  0.98313824 0.23202145 0.37748663 0.23386393]
 [0.85159374 0.17221038 0.41749765 0.52189143 0.71889232 0.62818505
  0.21822219 0.52276886 0.23691764 0.80435694]
 [0.36490591 0.65219483 0.99523104 0.18860701 0.47283385 0.11716605
  0.89291217 0.60614524 0.58507213 0.2354745 ]
 [0.88629505 0.69644403 0.68888982 0.42894543 0.39109914 0.67736274
  0.64120443 0.06385103 0.56384851 0.15581551]
 [0.06862947 0.90899091 0.92373002 0.13560061 0.12902422 0.8

In [ ]:
#Number_6
import numpy as np
zero_array = np.zeros(10)
zero_array[4] = 1
print(zero_array)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#number_7
arr = [1, 2, 0, 0, 4, 0]

# Reverse the array using slicing
reversed_arr = arr[::-1]

print(reversed_arr)


[0, 4, 0, 0, 2, 1]


In [ ]:
#number_8
import numpy as np

size = 5
array = np.ones((size, size))
array[1:-1, 1:-1] = 0

print(array)



[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#number_9
import numpy as np

matrix = np.zeros((8, 8), dtype=int)

matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1

print(matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


problem 3

In [ ]:
#question_1

import numpy as np
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

result = x + y

print(result)


[[ 6  8]
 [10 13]]


In [ ]:
#question_2
import numpy as np


x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])


result = x - y

print(result)


[[-4 -4]
 [-4 -3]]


In [ ]:
#question_3
import numpy as np

x = np.array([[1, 2], [3, 5]])
result = x * 2

print(result)


[[ 2  4]
 [ 6 10]]


In [ ]:
#question_4
import numpy as np

x = np.array([[1, 2], [3, 5]])
squared_result = x ** 2

print(squared_result)


[[ 1  4]
 [ 9 25]]


In [ ]:
#question_5
import numpy as np


x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)


print("Dot product of v and w:", dot_vw)
print("Dot product of x and v:", dot_xv)
print("Dot product of x and y:", dot_xy)


Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y: [[19 22]
 [50 58]]


In [ ]:
#question_6
# Concatenate x and y along rows
concat_xy_rows = np.concatenate((x, y), axis=0)


concat_vw_columns = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)

print("Concatenate x and y along rows:\n", concat_xy_rows)
print("Concatenate v and w along columns:\n", concat_vw_columns)


Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]


In [ ]:
#question_7
try:

    concat_xv = np.concatenate((x, v), axis=0)  # This will give an error
except ValueError as e:
    print("Error when concatenating x and v along rows:", e)

# Reshape v to match the shape of x and then concatenate along rows
v_reshaped = v.reshape(1, -1)
concat_xv_correct = np.concatenate((x, v_reshaped), axis=0)
print("Concatenate x and v after reshaping v:\n", concat_xv_correct)


Error when concatenating x and v along rows: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Concatenate x and v after reshaping v:
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


problem 4


In [ ]:

#given array
import numpy as np

# Define the matrices A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

In [ ]:
#question_1
# Calculate the inverse of A
A_inv = np.linalg.inv(A)

# Multiply A by A_inv
result_1 = np.dot(A, A_inv)

# Identity matrix (2x2)
I = np.eye(2)

print("A * A_inv =\n", result_1)
print("Identity matrix I =\n", I)

# Check if A * A_inv is approximately the identity matrix
print("Is A * A_inv approximately equal to I?", np.allclose(result_1, I))



A * A_inv =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity matrix I =
 [[1. 0.]
 [0. 1.]]
Is A * A_inv approximately equal to I? True


In [ ]:
#question_2
# Multiply A and B
AB = np.dot(A, B)

# Multiply B and A
BA = np.dot(B, A)

print("AB =\n", AB)
print("BA =\n", BA)

# Check if AB is equal to BA
print("Is AB equal to BA?", np.array_equal(AB, BA))


AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
Is AB equal to BA? False


In [ ]:
#question_3
# Compute the transpose of AB
AB_T = np.transpose(np.dot(A, B))

# Compute the product of B^T and A^T
BT_AT = np.dot(np.transpose(B), np.transpose(A))

print("Transpose of AB =\n", AB_T)
print("B^T * A^T =\n", BT_AT)

# Check if (AB)^T is equal to B^T * A^T
print("Is (AB)^T equal to B^T * A^T?", np.array_equal(AB_T, BT_AT))


Transpose of AB =
 [[23 51]
 [13 29]]
B^T * A^T =
 [[23 51]
 [13 29]]
Is (AB)^T equal to B^T * A^T? True


In [ ]:
#Linera equation using inverse methods.
import numpy as np

# Define the matrix A (coefficients) and B (constants)
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

# Compute the inverse of A
A_inv = np.linalg.inv(A)

# Solve for X using the inverse method
X = np.dot(A_inv, B)

# Print the solution
print("Solution [x, y, z]:", X)


Solution [x, y, z]: [ 2.  1. -2.]


In [ ]:
#4.2 Experiment
#number_1
import numpy as np
import time

# Create two Python lists of size 1,000,000
list1 = list(range(1_000_000))
list2 = list(range(1_000_000))

# Measure time for element-wise addition using Python lists
start_time_list = time.time()
list_result = [list1[i] + list2[i] for i in range(len(list1))]
end_time_list = time.time()

# Time taken for Python lists
list_time = end_time_list - start_time_list
print(f"Time taken for element-wise addition using Python lists: {list_time:.5f} seconds")

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1_000_000)
array2 = np.arange(1_000_000)

# Measure time for element-wise addition using NumPy arrays
start_time_array = time.time()
array_result = array1 + array2
end_time_array = time.time()

# Time taken for NumPy arrays
array_time = end_time_array - start_time_array
print(f"Time taken for element-wise addition using NumPy arrays: {array_time:.5f} seconds")


Time taken for element-wise addition using Python lists: 0.16040 seconds
Time taken for element-wise addition using NumPy arrays: 0.00576 seconds


In [ ]:
#number_2
import numpy as np
import time

# Create two Python lists of size 1,000,000
list1 = list(range(1_000_000))
list2 = list(range(1_000_000))

# Measure time for element-wise multiplication using Python lists
start_time_list = time.time()
list_result = [list1[i] * list2[i] for i in range(len(list1))]
end_time_list = time.time()

# Time taken for Python lists
list_time = end_time_list - start_time_list
print(f"Time taken for element-wise multiplication using Python lists: {list_time:.5f} seconds")

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1_000_000)
array2 = np.arange(1_000_000)

# Measure time for element-wise multiplication using NumPy arrays
start_time_array = time.time()
array_result = array1 * array2
end_time_array = time.time()

# Time taken for NumPy arrays
array_time = end_time_array - start_time_array
print(f"Time taken for element-wise multiplication using NumPy arrays: {array_time:.5f} seconds")


Time taken for element-wise multiplication using Python lists: 0.15384 seconds
Time taken for element-wise multiplication using NumPy arrays: 0.00519 seconds


In [ ]:
#number_3
import numpy as np
import time

# Create two Python lists of size 1,000,000
list1 = list(range(1_000_000))
list2 = list(range(1_000_000))

# Measure time for dot product using Python lists
start_time_list = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(len(list1)))
end_time_list = time.time()

# Time taken for Python lists
list_time = end_time_list - start_time_list
print(f"Time taken for dot product using Python lists: {list_time:.5f} seconds")
print(f"Dot product using Python lists: {dot_product_list}")

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1_000_000)
array2 = np.arange(1_000_000)

# Measure time for dot product using NumPy arrays
start_time_array = time.time()
dot_product_array = np.dot(array1, array2)
end_time_array = time.time()

# Time taken for NumPy arrays
array_time = end_time_array - start_time_array
print(f"Time taken for dot product using NumPy arrays: {array_time:.5f} seconds")
print(f"Dot product using NumPy arrays: {dot_product_array}")


Time taken for dot product using Python lists: 0.18162 seconds
Dot product using Python lists: 333332833333500000
Time taken for dot product using NumPy arrays: 0.00165 seconds
Dot product using NumPy arrays: 333332833333500000


In [ ]:
#number_4
import numpy as np
import time

# Using Python Lists
# Create two 1000x1000 matrices as Python lists
matrix1 = [[i * j for j in range(1000)] for i in range(1000)]
matrix2 = [[i + j for j in range(1000)] for i in range(1000)]

# Measure time for matrix multiplication using Python lists
start_time_list = time.time()
result_list = [[sum(a * b for a, b in zip(row, col)) for col in zip(*matrix2)] for row in matrix1]
end_time_list = time.time()

# Time taken for Python lists
list_time = end_time_list - start_time_list
print(f"Time taken for matrix multiplication using Python lists: {list_time:.5f} seconds")

# Using NumPy
# Create two 1000x1000 matrices as NumPy arrays
array1 = np.random.randint(0, 10, (1000, 1000))
array2 = np.random.randint(0, 10, (1000, 1000))

# Measure time for matrix multiplication using NumPy arrays
start_time_array = time.time()
result_array = np.dot(array1, array2)
end_time_array = time.time()

# Time taken for NumPy arrays
array_time = end_time_array - start_time_array
print(f"Time taken for matrix multiplication using NumPy arrays: {array_time:.5f} seconds")


Time taken for matrix multiplication using Python lists: 225.41109 seconds
Time taken for matrix multiplication using NumPy arrays: 1.43169 seconds
